from PyQt4 import QtCore, QtGui


class ControlGroup(QtGui.QWidget):
    def __init__(self, mode):
        QtGui.QWidget.__init__(self)

        self.grain_use = QtGui.QTableWidget()
        self.grain_use.setColumnCount(3)
        self.grain_use.setRowCount(6)
        self.grain_use.setAlternatingRowColors(True)
        self.grain_use.setHorizontalHeaderLabels(['Grain', 'Kg.', '%'])
        self.grain_use.verticalHeader().setVisible(False)
        self.grain_use.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.grain_use.setSelectionMode(QtGui.QAbstractItemView.
                                               NoSelection)
        gr_use_header = self.grain_use.horizontalHeader()
        gr_use_header.setResizeMode(QtGui.QHeaderView.Stretch)

        self.hop_use = QtGui.QTableWidget()
        self.hop_use.setColumnCount(3)
        self.hop_use.setRowCount(6)
        self.hop_use.setAlternatingRowColors(True)
        self.hop_use.setHorizontalHeaderLabels(['Hop', 'Grams', 'Minutes'])
        self.hop_use.verticalHeader().setVisible(False)
        self.hop_use.setDragDropMode(QtGui.QAbstractItemView.DropOnly)
        self.hop_use.setSelectionMode(QtGui.QAbstractItemView.
                                               NoSelection)
        hop_use_header = self.hop_use.horizontalHeader()
        hop_use_header.setResizeMode(QtGui.QHeaderView.Stretch)

        mash_temp_box = QtGui.QGroupBox('Mash Temp')
        mash_temp_box.setMinimumHeight(30)
        self.mash_temp_disp = QtGui.QLineEdit('0')
        self.mash_temp_disp.setMinimumHeight(20)
        self.mash_temp_disp.setAlignment(QtCore.Qt.AlignCenter)
        mtb_layout = QtGui.QVBoxLayout()
        mash_temp_box.setLayout(mtb_layout)
        mtb_layout.addWidget(self.mash_temp_disp)

        mash_eff_box = QtGui.QGroupBox('Mash Eff')
        mash_eff_box.setMinimumHeight(30)
        self.mash_eff_disp = QtGui.QLineEdit('0')
        self.mash_eff_disp.setMinimumHeight(20)
        self.mash_eff_disp.setAlignment(QtCore.Qt.AlignCenter)
        mef_layout = QtGui.QVBoxLayout()
        mash_eff_box.setLayout(mef_layout)
        mef_layout.addWidget(self.mash_eff_disp)

        vol_box = QtGui.QGroupBox('Volume')
        vol_box.setMinimumHeight(30)
        self.vol_disp = QtGui.QLineEdit('0')
        self.vol_disp.setMinimumHeight(20)
        self.vol_disp.setAlignment(QtCore.Qt.AlignCenter)
        vol_layout = QtGui.QVBoxLayout()
        vol_box.setLayout(vol_layout)
        vol_layout.addWidget(self.vol_disp)

        ebu_box = QtGui.QGroupBox('EBU')
        ebu_box.setMinimumHeight(30)
        self.ebu_disp = QtGui.QLineEdit('0')
        self.ebu_disp.setMinimumHeight(20)
        self.ebu_disp.setAlignment(QtCore.Qt.AlignCenter)
        ebu_layout = QtGui.QVBoxLayout()
        ebu_box.setLayout(ebu_layout)
        ebu_layout.addWidget(self.ebu_disp)

        ebc_box = QtGui.QGroupBox('EBC')
        ebc_box.setMinimumHeight(30)
        self.ebc_disp = QtGui.QLineEdit('0')
        self.ebc_disp.setMinimumHeight(20)
        self.ebc_disp.setAlignment(QtCore.Qt.AlignCenter)
        ebc_layout = QtGui.QVBoxLayout()
        ebc_box.setLayout(ebc_layout)
        ebc_layout.addWidget(self.ebc_disp)

        og_box = QtGui.QGroupBox('OG')
        og_box.setMinimumHeight(30)
        self.og_disp = QtGui.QLineEdit('0')
        self.og_disp.setMinimumHeight(20)
        self.og_disp.setAlignment(QtCore.Qt.AlignCenter)
        og_layout = QtGui.QVBoxLayout()
        og_box.setLayout(og_layout)
        og_layout.addWidget(self.og_disp)

        button_bar = QtGui.QHBoxLayout()

        if mode == 'new':
            self.button_write_notes = QtGui.QPushButton('Write Notes')
            self.button_save_brew = QtGui.QPushButton('Save Brew')
            self.button_commit = QtGui.QPushButton('Commit')
            self.button_write_notes.setMinimumHeight(20)
            self.button_save_brew.setMinimumHeight(20)
            self.button_commit.setMinimumHeight(20)
            button_bar.addWidget(self.button_write_notes)
            button_bar.addWidget(self.button_save_brew)
            button_bar.addWidget(self.button_commit)
        else:
            self.button_use_recipe = QtGui.QPushButton('Use Recipe')
            self.button_use_recipe.setMinimumHeight(20)
            button_bar.addWidget(self.button_use_recipe)

        top_display = QtGui.QHBoxLayout()
        top_display.addWidget(mash_temp_box)
        top_display.addWidget(mash_eff_box)
        top_display.addWidget(vol_box)

        bot_display = QtGui.QHBoxLayout()
        bot_display.addWidget(ebu_box)
        bot_display.addWidget(ebc_box)
        bot_display.addWidget(og_box)

        control_box = QtGui.QGroupBox()
        control_layout = QtGui.QVBoxLayout()
        control_box.setLayout(control_layout)
        control_layout.addLayout(top_display)
        control_layout.addLayout(bot_display)
        control_layout.addLayout(button_bar)

        layout = QtGui.QHBoxLayout()
        self.setLayout(layout)
        layout.addWidget(self.grain_use)
        layout.addWidget(self.hop_use)
        layout.addWidget(control_box)
